#!/bin/bash
if [ "$STAGIUM_PATH" == "" ] 
then 
  STAGIUM_PATH="`dirname \"$0\"`"                  # relative
  STAGIUM_PATH="`( cd \"$STAGIUM_PATH\" && pwd )`"  # absolutized and normalized
fi
if [ "$SCALA_PATH_211" == "" ] 
then
  SCALA_PATH_211="`dirname $(which scalac)`"
  SCALA_PATH_211="`( cd \"$SCALA_PATH_211\" && pwd )`"
fi

if [ "$STAGIUM_PATH" == "" -o "$SCALA_PATH_211" == "" -o ! -f $SCALA_PATH_211/scalac -o ! -d $STAGIUM_PATH/components ]
then
  echo To use this script please set the STAGIUM_PATH and SCALA_PATH_211 environment variables such that:
  echo " -" '$SCALA_PATH_211/scalac' "(currently $SCALA_PATH_211/scalac)"
  echo " -" '$STAGIUM_PATH/components' "(currently $STAGIUM_PATH/components)"
  echo are accessible
  exit 1
fi

SCALA_VERSION=2.11
STAGIUM_VERSION=0.1-SNAPSHOT
PLUGIN_JAR=$STAGIUM_PATH/components/plugin/target/scala-$SCALA_VERSION/stagium-plugin_$SCALA_VERSION-$STAGIUM_VERSION.jar
RUNTIME_JAR=$STAGIUM_PATH/components/runtime/target/scala-$SCALA_VERSION/stagium-runtime_$SCALA_VERSION-$STAGIUM_VERSION.jar

me=`basename $0`
if [ "$me" == "st-scalac" ]; then
  target=scalac
elif [ "$me" == "st-scala" ]; then
  target=scala
else
  echo Unrecognized script name: $0
  exit 1
fi

function checkjar {
  if [ ! -f "$1" ]
  then
    echo "The script is going to build the required jar file $1 by running \"sbt $2\" [5s until build]"
    sleep 5
    cd $STAGIUM_PATH
    sbt $2
    cd -
    if [ ! -f "$1" ]
    then
      echo "The required jar file has not been built by sbt. Please run \"sbt $2\""
      exit 1
    else
      echo "The required jar file was built."
    fi
  fi
}

checkjar $PLUGIN_JAR stagium-plugin/package
checkjar $RUNTIME_JAR stagium-runtime/package

$SCALA_PATH_211/$target -bootclasspath $RUNTIME_JAR:$PLUGIN_JAR -Xplugin:$PLUGIN_JAR $@
